# Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages: []

footer: ''

style: light # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag
